project:
  type: website

website:
  title: "dog_murder_mistery_game"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: suspects/dogs_index.qmd
        text: "🐾 Suspects"

format:
  html:
    theme:
      - sketchy
      - brand
    css: styles.css
    toc: true



