project:
  type: website

website:
  title: "Paw & Order: The Broken Pipe Unit"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: suspects/dog_index.qmd
        text: "Suspects"
      - href: result_index.qmd
        text: "Give your verdict"

format:
  html:
    theme:
      - sketchy
      - brand
    css: styles.css
    toc: true



