project:
  type: website
  resources:
    - dog_portraits/06_mugshot.png
    - dog_portraits/07_escape.png

website:
  title: "Paw & Order: The Broken Pipe Unit"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: suspects/dog_index.qmd
        text: "Suspects"
      - href: result_index.qmd
        text: "Give your veredict"

format:
  html:
    theme:
      - sketchy
      - brand
    css: styles.css
    toc: true



